config/routes.rb
Rails.application.routes.draw do
  get "home", to: "home#show"
  root "home#show"

  resources :arts do
    resources :reviews, only: [:new, :create, :destroy]
    resources :photos, only: :create
  end

  resources :reviews, only: [:edit, :update] do
    resources :votes, only: [:create]
  end

  namespace :admin do
    resources :users, only: [:index, :update, :destroy]
  end

  devise_for :users, controllers: {
    registrations: "registrations",
    sessions: "sessions"
  }

  get '/search' => 'search#index'
end

app/models/art.rb
class Art < ActiveRecord::Base
  include PgSearch
  pg_search_scope :search_by_name, against: :name, using: {
    tsearch: {
      prefix: true
    }
  }

  belongs_to :user
  has_many :reviews
  has_many :photos

  validates :name, presence: true
  validates :location, presence: true
  validates :description, presence: true
  validates :category, presence: true
  validates :user, presence: true

  accepts_nested_attributes_for :photos, allow_destroy: true
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :art_photo, ArtPhotoUploader
  belongs_to :art

  validates :art_photo, presence: true
  validates :art, presence: true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :art
  belongs_to :user
  has_many :votes

  validates :body, presence: true
  validates :rating, presence: true, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 1,
    less_than_or_equal_to: 5,
  }
  validates :user_id, presence: true
  validates :art_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :arts
  has_many :reviews
  has_many :votes

  mount_uploader :profile_photo, ProfilePhotoUploader

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true

  devise :database_authenticatable,
    :registerable,
    :recoverable,
    :rememberable,
    :trackable,
    :validatable

  def full_name
    "#{first_name} #{last_name}"
  end

  def admin?
    role == 'admin'
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :review

  validates :upvote, inclusion: { in: [true, false, 1, 0] }
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user

  def index
    if current_user.admin?
      @users = User.all
    else
      raise_error
    end
  end

  def update
    user = User.find(params[:id])
    if user.admin?
      user.role = 'member'
    else
      user.role = 'admin'
    end
    user.save
    redirect_to admin_users_path
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to admin_users_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [
      :first_name,
      :last_name,
      :profile_photo
    ]

    devise_parameter_sanitizer.for(:account_update) << :profile_photo
  end

  def authenticate_user
    if !user_signed_in?
      raise_error
    end
  end

  def raise_error
    raise ActionController::RoutingError.new("Not Found")
  end
end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
  before_action :authenticate_user, except: [:index, :show]

  def index
    @arts = Art.all.order("id ASC").page(params[:page])
  end

  def new
    @art = Art.new
  end

  def show
    @art = Art.find(params[:id])
    @photos = @art.photos
    @photo = Photo.new
    @reviews = @art.reviews.page(params[:page])
  end

  def create
    @art = Art.new(art_params)
    @art.user = current_user
    if @art.save
      flash[:notice] = "Art successfully added!"
      respond_to { |format| format.html { redirect_to art_path(@art) } }
    else
      flash[:error] = @art.errors.full_messages.join('. ')
      render :new
    end
  end

  def edit
    @art = Art.find(params[:id])
    unless @art.user == current_user
      raise_error
    end
  end

  def update
    @art = Art.find(params[:id])
    if @art.update_attributes(art_params)
      redirect_to @art
    else
      flash[:notice] = "You must fill out all of the required fields"
      render :edit
    end
  end

  def destroy
    @arts = Art.all.order("id ASC")
    @art = Art.find(params[:id])
    @art.destroy

    redirect_to arts_path
  end

  private

  def art_params
    params.require(:art).permit(
      :name,
      :location,
      :description,
      :category,
      :artist
    )
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    @arts = Art.first(6)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def create
    @photo = Photo.new(photo_params)
    @photo.art_id = params[:art_id]
    if @photo.save
      flash[:notice] = "Photo successfully added!"
    else
      flash[:error] = @photo.errors.full_messages.join('. ')
    end
    redirect_to art_path(params[:art_id])
  end

  private

  def photo_params
    params.require(:photo).permit(
      :art_photo,
      :caption
    )
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  # def after_sign_up_path_for(_resource)
  #   flash[:notice] = "You're in!"
  #   :edit_user_registration
  # end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user, except: [:index, :show]

  def new
    @art = Art.find(params[:art_id])
    @review = Review.new
  end

  def create
    @art = Art.find(params[:art_id])
    @review = @art.reviews.new(review_params)
    @review.user = current_user
    if @review.save
      # ReviewMailer.new_review(@review).deliver_later
      redirect_to art_path(@art)
    else
      flash[:errors] = @review.errors.full_messages.join(". ")
      render :new
    end
  end

  def edit
    @review = Review.find(params[:id])
    unless @review.user == current_user
      raise_error
    end
    @review.art = @art
  end

  def update
    @review = Review.find(params[:id])
    if @review.update_attributes(review_params)
      redirect_to art_path(@review.art)
    else
      flash[:notice] = "You must fill out all of the required fields"
      render :edit
    end
  end

  def destroy
      @art = Art.find(params[:art_id])
      Review.find(params[:id]).destroy

      redirect_to art_path(@art)
  end

  private

  def review_params
    params.require(:review).permit(:body, :rating, :art_id)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    if params[:query]
      @arts = Art.where("name ILIKE ?", "%#{params[:query]}%")
    end

    if @arts.empty? || params[:query].empty?
      flash[:notice] = "Sorry, no results."
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  protected

  # def after_sign_in_path_for(_resource)
  #   :edit_user_registration
  # end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    new_vote = params[:newVote]
    r_id = params[:rId].to_i

    vote = Vote.find_by(user: current_user, review_id: r_id)

    if vote
      if vote.upvote == (new_vote == 'upvote')
        vote.destroy
      else
        vote.upvote = !vote.upvote
        vote.save
      end
    else
      Vote.create(
        user: current_user,
        review_id: r_id,
        upvote: new_vote == 'upvote'
      )
    end

    render json: {
      upvotes: Vote.where(review_id: r_id, upvote: true).count,
      downvotes: Vote.where(review_id: r_id, upvote: false).count
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/users/index.html.erb
<h1>All Users</h1>

<table>
  <tr>
    <td>Name</td>
    <td>Email</td>
    <td>Role</td>
    <td>Action</td>
    <td></td>
  </tr>
  <% @users.each do |user| %>
  <tr>
    <td> <%= user.full_name %></td>
    <td> <%= user.email %></td>
    <td> <%= user.role %></td>
    <td>
      <%= button_to "Delete",
        admin_user_path(user),
        method: :delete,
        id: "delete_#{user.id}" %>
    </td>
    <td>
      <% unless current_user == user %>
        <% if user.role == 'admin' %>
          <%= button_to "Remove Admin Privilege",
            admin_user_path(user),
            method: :put %>
        <% else %>
          <%= button_to "Make Admin",
            admin_user_path(user),
            method: :put %>
        <% end %>
      <% end %>
    </td>
  </tr>
  <% end %>
</table>

app/views/arts/_form.html.erb
<%= form_for(@art) do |f| %>

  <div class="field">
    <%= f.label "Name:" %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label "Artist:"%>
    <%= f.text_field :artist %>
  </div>

  <div class="field">
    <%= f.label "Location:" %>
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label "Category (Mural or Graffiti):" %>
    <%= f.text_field :category %>
  </div>

  <div class="field">
    <%= f.label "Description:" %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit class: "button round form-button" %>
  </div>
<% end %>

app/views/arts/_new_art.html.erb
<%= form_for [@art, @photo] do |f| %>
  <div class="upload-image">
    <%= f.label :art_photo, 'Upload a Photo' %>
    <%= f.file_field :art_photo %>
  </div>

  <div class="upload-image caption">
    <%= f.label :caption, 'Caption' %>
    <%= f.text_area :caption %>
  </div>

  <div class="actions">
    <%= f.submit class: "button round form-button" %>
  </div>
<% end %>

app/views/arts/_new_form.html.erb
<%= form_for(@art) do |f| %>
  <div class="field">
    <%= f.label "Name:" %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label "Artist:"%>
    <%= f.text_field :artist %>
  </div>

  <div class="field">
    <%= f.label "Location:" %>
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label "Category:" %>
    <%= f.text_field :category %>
  </div>

  <div class="field">
    <%= f.label "Description:" %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit "Add New Art", class: 'button small round form_button' %>
  </div>
<% end %>

app/views/arts/_photo.html.erb
<div class="image full_width">
  <div class="orbit-photo">
    <%= image_tag photo.art_photo %>
    <div class="caption">
      <%= photo.caption %>
    </div>
  </div>
</div>

app/views/arts/edit.html.erb
<h1>Edit Art Information</h1>

<div class="row">
  <div class="small-6 small-centered columns border">
    <%= render 'form' %>
  </div>
</div>

<div class="row">
  <div class="small-6 small-centered columns back-link">
    <%= link_to "Back to Arts", arts_path %>
  </div>
</div>

app/views/arts/index.html.erb
<h1>iSpy Gallery</h1>
<ul class="medium-block-grid-3">
  <% @arts.each do |art| %>
    <li>
      <% if art.photos.first %>
        <%= link_to image_tag(art.photos.first.art_photo), art_path(art), class: 'index-photo' %>
      <% end %>
      <span class="label"><%= link_to "#{art.name}, #{art.artist}", art_path(art) %></span>
    </li>
  <% end %>
</ul>
<%= paginate @arts %>

app/views/arts/new.html.erb
<h1>Add Some Sweet Street Art!</h1>

<div class="row">
  <div class="small-6 small-centered columns border">
    <%= render 'form' %>
  </div>
</div>

<div class="row">
  <div class="small-6 small-centered columns back-link">
    <%= link_to "Back to Arts", arts_path %>
  </div>
</div>

app/views/arts/show.html.erb
<h1><%= @art.name %></h1>

<div class="small-11 small-centered columns">
  <div class="picture-container">
<!-- <div class="orbit-container">
  <ul class="show-orbit" data-orbit> -->
    <%= render partial: "photo", collection: @photos %>
  <!-- </ul> -->
 </div>
</div>

<div class="row">
  <div class="small-6 small-centered columns border photo-form">
    <% if user_signed_in? %>
      <h2>Add a Photo</h2>
      <%= render 'new_art' %>
    <% else %>
      <%= link_to "Sign in to add a photo", new_user_session_path, class: "tiny button round form-button sign-in-to-add-photo" %>
    <% end %>
  </div>
</div>

<div class="art-details">
  <ul>
    <% if @art.artist.present? %>
    <li><u>Artist:</u> <%= @art.artist %></li>
    <% end %>
    <li><u>Location:</u> <%= @art.location %></li>
    <li><u>Category:</u> <%= @art.category %></li>
    <li><u>Description:</u> <%= @art.description %></li>
  </ul>
</div>

<% @reviews.each do |review|  %>
  <div class="review">
    <% if user_signed_in? %>
      <% if current_user.admin? || review.user == current_user %>
        <ul class="user-specific-content">
          <li><%= link_to "Edit this Review", edit_review_path(review), class: "tiny button round form-button edit-review"%></li>
          <li><%= link_to "Delete this Review", art_review_path(@art, review), method: :delete, class: "tiny button round form-button delete-review" %></li>
        </ul>
      <% end %>
      <div class="vote-buttons">
        <%= button_to pluralize(review.votes.where(upvote: true).count,
          "Upvote"),
          art_path(@art),
          method: 'get',
          class: 'votes up',
          id: "upvote-#{review.id}" %>
        <%= button_to pluralize(review.votes.where(upvote: false).count,
          "Downvote"),
          art_path(@art),
          method: 'get',
          class: 'votes down',
          id: "downvote-#{review.id}" %>
      </div>
    <% else %>
      <%= link_to 'Sign in to upvote or downvote this review!', new_user_session_path %>
    <% end %>
    <ul class="review-content">
      <li>
        <% if review.user.profile_photo? %>
          <%= image_tag review.user.profile_photo_url, class: 'nav-img review-img' %>
        <% else %>
          <%= image_tag 'default_photo.png', class: 'nav-img review-img' %>
        <% end %>
        <%= review.user.first_name %> <%= review.user.last_name %>
      </li>
      <li><strong>Rating:</strong> <%= review.rating %></li>
      <li><strong>Comments:</strong> <%= review.body %></li>
    </ul>
  </div>
<% end %>

<%= paginate @reviews %>

<div class="art_actions actions">
  <ul class="art-buttons">
    <% if user_signed_in? %>
      <li><%= link_to "Add New Review", new_art_review_path(@art), class: "small button round form-button"%></li>
      <% if current_user.admin? || @art.user == current_user%>
        <li><%= link_to "Edit this Entry", edit_art_path(@art), class: "small button round form-button" %></li>
        <li><%= link_to "Delete this Entry", art_path(@art), method: :delete, class: "small button round form-button" %></li>
      <% end %>
    <% else %>
      <li><%= link_to 'Sign in to add a new review!', new_user_session_path,  class: "small button round form-button" %></li>
    <% end %>
    <li><%= link_to "Home", root_path, class: "small button round form-button" %></li>
  </ul>
</div>

<%= javascript_include_tag "show" %>

app/views/home/show.html.erb
<h1> iSpy: Street Art in Review </h1>

  <div class="small-11 small-centered columns">
    <div class="picture-container">
        <div>
          <%= image_tag "fox.jpg" %>
        </div>

        <div>
          <%= image_tag "dublin.jpg" %>
        </div>

        <div>
          <%= image_tag "graffiti.jpg" %>
        </div>
        <div>
            <%= image_tag "city-love-rainbow-nyc.jpg" %>
        </div>
      </div>
  </div>

  <div class="row">
    <div class="small-6 large-centered columns about"><h2>Welcome to iSpy!</h2>
    <p> We are a group of rag-tag computer programmers who needed a BADASS project to take over the world. Join us in our journey to success. </p></div>
  </div>

  <div class="row">
    <div class="medium-5 columns new"><h3>
      <% if user_signed_in? %>
      <%= link_to "Add New Street Art", new_art_path %>
      <% else %>
        <%= link_to "Sign in to add new street art!", new_user_session_path %>
      <% end %>
    </h3></div>
    <div class="medium-5 columns all-art"><h3><%= link_to "View All Art", arts_path %></h3></div>
  </div>

<h1> iSpy Gallery </h1>
  <ul class="medium-block-grid-3">
    <% @arts.each do |art| %>
      <li>
        <% if art.photos.first %>
          <%= link_to image_tag(art.photos.first.art_photo), art_path(art), class: 'index-photo' %>
        <% end %>
        <span class="label"><%= link_to "#{art.name} by #{art.artist}", art_path(art) %></span>
      </li>
    <% end %>
  </ul>

<center><a href="/arts" class="med button round"> View More</a></center>

app/views/layouts/_nav.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "iSpy", root_path %></h1>
    </li>

    <li class="toggle-topbar menu-icon"><a href="/"><span>iSpy</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->

    <ul class="right">
      <li class="has-form">
        <div class="search-bar">
         <%= form_tag("/search", method: 'get') do %>
           <span><%= text_field_tag :query, params[:query] %></span>
           <span><%= submit_tag "Search", :name => nil, class: "search-button" %></span>
         <% end %>
       </div>
     </li>
      <% if user_signed_in? %>
      <% if current_user.admin? %>
        <li><%= link_to "All Users", admin_users_path %></li>
      <% end %>
        <li class="has-dropdown">
         <a href="#">
           <% if current_user.profile_photo? %>
            <%= image_tag current_user.profile_photo_url, class: 'nav-img' %>
          <% else %>
            <%= image_tag 'default_photo.png', class: 'nav-img' %>
          <% end %>
          <%= current_user.full_name %>
        </a>
          <ul class="dropdown">
            <li><%= link_to "Edit Account", edit_user_registration_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to "Sign In!", new_user_session_path %></li>
        <li><%= link_to "Sign Up Here!", new_user_registration_path %></li>
      <%end%>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href='https://fonts.googleapis.com/css?family=Ubuntu:400,300italic' rel='stylesheet' type='text/css'>

    <title><%= content_for?(:title) ? yield(:title) : "iSpy" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render "layouts/nav" %>

    <div class="row">
      <div class="small-6 small-centered column">
        <div class="flash">
          <% flash.each do |key, value| %>
            <div data-alert class="alert-box round <%= key.to_s == 'notice' ? 'success' : 'alert' %>">
            <%= content_tag :div, value %>
            <a href="#" class="close">&times;</a>
          <% end %>
        </div>
      </div>
    </div>

    <%= yield %>

    <footer class="footer">
      <div class="row">
        <div class="small-12 columns">
          <p class="slogan">iSpy: Street Art in Review</p>
          <p class="links">
            <%= link_to "Home", root_path %>
            <%= link_to "View All Art", arts_path %>
            <% if user_signed_in? %>
              <%= link_to "Add Art", new_art_path %>
            <% else %>
              <%= link_to "Sign In", new_user_session_path %>
            <% end %>
          </p>
          <!-- <p class="copywrite">Copywrite not copypwrite © 2015</p> -->
        </div>
      </div>
    </footer>

  </body>
</html>

app/views/reviews/_edit_form.html.erb
<%= form_for(@review) do |f| %>
<div class="field">
  <%= f.label :body, "Comment" %>
  <%= f.text_field :body %>
</div>

<div class="field">
  <%= f.label :rating, "rating"%>
  <%= f.text_field :rating %>
</div>
<div class="actions">
  <%= f.submit "Update Review" %>
</div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<div class="row">
  <div class="small-6 small-centered columns border">
    <%= render 'edit_form' %>
  </div>
</div>

<div class="row">
  <div class="small-6 small-centered columns back-link">
    <%= link_to "Back to Arts", arts_path %>
  </div>
</div>

app/views/reviews/new.html.erb
<h1>New Review for <%= @art.name %> </h1>

<div class="row">
  <div class="small-6 small-centered columns border">
    <%= form_for [@art, @review] do |f| %>
      <div class="field">
        <%= f.label :rating, "Rating"%>
        <%= f.text_field :rating %>
      </div>

      <div class="field">
        <%= f.label :body, "Comments" %>
        <%= f.text_field :body %>
      </div>
      <div class="actions ">
        <%= f.submit class: "button round form-button" %>
      </div>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="small-6 small-centered columns back-link">
    <%= link_to "Back", art_path(@art) %>
  </div>
</div>

app/views/search/index.html.erb
<h1>Results</h1>

<ol>
  <% @arts.each do |art| %>
    <li>
      <%= link_to art.name, art_path(art) %>
    </li>
  <% end %>
</ol>